#!/bin/bash
#
#
# +--------------------------------+
# |     VARIABLE DEFINITIONS       |
# +--------------------------------+
#
#
# A fantastic list of colour definitions:
#  https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux

# Reset
COLOUR_OFF='\033[0m'       # Text Reset

# Regular Colors
BLACK='\033[0;30m'        # BLACK
RED='\033[0;31m'          # RED
GREEN='\033[0;32m'        # GREEN
YELLOW='\033[0;33m'       # YELLOW
BLUE='\033[0;34m'         # BLUE
PURPLE='\033[0;35m'       # PURPLE
CYAN='\033[0;36m'         # CYAN
WHITE='\033[0;37m'        # WHITE

# Bold
BOLD_BLACK='\033[1;30m'       # BLACK
BOLD_RED='\033[1;31m'         # RED
BOLD_GREEN='\033[1;32m'       # GREEN
BOLD_YELLOW='\033[1;33m'      # YELLOW
BOLD_BLUE='\033[1;34m'        # BLUE
BOLD_PURPLE='\033[1;35m'      # PURPLE
BOLD_CYAN='\033[1;36m'        # CYAN
BOLD_WHITE='\033[1;37m'       # WHITE

# Underline
UNDER_BLACK='\033[4;30m'       # BLACK
UNDER_RED='\033[4;31m'         # RED
UNDER_GREEN='\033[4;32m'       # GREEN
UNDER_YELLOW='\033[4;33m'      # YELLOW
UNDER_BLUE='\033[4;34m'        # BLUE
UNDER_PURPLE='\033[4;35m'      # PURPLE
UNDER_CYAN='\033[4;36m'        # CYAN
UNDER_WHITE='\033[4;37m'       # WHITE

# Background
BG_BLACK='\033[40m'       # BLACK
BG_RED='\033[41m'         # RED
BG_GREEN='\033[42m'       # GREEN
BG_YELLOW='\033[43m'      # YELLOW
BG_BLUE='\033[44m'        # BLUE
BG_PURPLE='\033[45m'      # PURPLE
BG_CYAN='\033[46m'        # CYAN
BG_WHITE='\033[47m'       # WHITE

# High Intensity
HI_BLACK='\033[0;90m'       # BLACK
HI_RED='\033[0;91m'         # RED
HI_GREEN='\033[0;92m'       # GREEN
HI_YELLOW='\033[0;93m'      # YELLOW
HI_BLUE='\033[0;94m'        # BLUE
HI_PURPLE='\033[0;95m'      # PURPLE
HI_CYAN='\033[0;96m'        # CYAN
HI_WHITE='\033[0;97m'       # WHITE

# Bold High Intensity
BHI_BLACK='\033[1;90m'      # BLACK
BHI_RED='\033[1;91m'        # RED
BHI_GREEN='\033[1;92m'      # GREEN
BHI_YELLOW='\033[1;93m'     # YELLOW
BHI_BLUE='\033[1;94m'       # BLUE
BHI_PURPLE='\033[1;95m'     # PURPLE
BHI_CYAN='\033[1;96m'       # CYAN
BHI_WHITE='\033[1;97m'      # WHITE

# High Intensity backgrounds
BG_HI_BLACK='\033[0;100m'   # BLACK
BG_HI_RED='\033[0;101m'     # RED
BG_HI_GREEN='\033[0;102m'   # GREEN
BG_HI_YELLOW='\033[0;103m'  # YELLOW
BG_HI_BLUE='\033[0;104m'    # BLUE
BG_HI_PURPLE='\033[0;105m'  # PURPLE
BG_HI_CYAN='\033[0;106m'    # CYAN
BG_HI_WHITE='\033[0;107m'   # WHITE#
#
# +--------------------------------+
# |     FUNCTION DEFINITIONS       |
# +--------------------------------+
#
#
#
# Print info/success messages
function print_info() {
    local INPUT=$1
    printf "${CYAN}[  INFO     ] ${INPUT}${COLOUR_OFF}\n"
}
#
# Print info/success messages
function print_success() {
    local INPUT=$1
    printf "${GREEN}[  SUCCESS  ] ${INPUT}${COLOUR_OFF}\n"
}
#
#
#
# Print warning messages
function print_warn() {
    local INPUT=$1
    printf "${YELLOW}[  WARNING  ] ${INPUT}${COLOUR_OFF}\n"
}
#
#
#
# Print error messages
function print_error() {
    local INPUT=$1
    printf "${RED}[  ERROR    ] ${INPUT}${COLOUR_OFF}\n"
}
